development:
  adapter: postgresql
  database: phphoto_development
  host: localhost
  username: postgres
  password: 
  pool: 8

test:
  adapter: postgresql
  database: phphoto_test
  pool: 8
  timeout: 5000

production:
  adapter: postgresql
  database: phphoto_production
  host: localhost
  username: postgres
  password: 
  pool: 8